services:
  back:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    container_name: back
  front:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    container_name: front